### ISSUE TITLE
最新的版本不work了

### ISSUE THREAD

**Issue by ArnoChenFx** [yym68686/uni-api#30]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    return await self.app(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__

    await super().__call__(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__

    raise exc

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__

    await self.app(scope, receive, _send)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__

    with collapse_excgroups():

  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/local/lib/python3.10/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 187, in __call__

    response = await self.dispatch_func(request, call_next)

  File "/home/main.py", line 633, in ensure_config

    return await call_next(request)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next

    raise app_exc

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__

    with collapse_excgroups():

  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/local/lib/python3.10/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 187, in __call__

    response = await self.dispatch_func(request, call_next)

  File "/home/main.py", line 493, in dispatch

    response = await call_next(request)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next

    raise app_exc

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app

    await route.handle(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app

    response = await f(request)

  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app

    solved_result = await solve_dependencies(

  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 638, in solve_dependencies

    solved = await call(**solved_result.values)

  File "/home/main.py", line 1054, in rate_limit_dependency

    if await rate_limiter.is_rate_limited(rate_limit_key, limits):

  File "/home/utils.py", line 50, in is_rate_limited

    for limit, period in limits:

TypeError: cannot unpack non-iterable int object
```

**Comment by yym68686** [comment]
应该修复好了。感谢测试。❤️
