### ISSUE TITLE
docker版本启动报错

### ISSUE THREAD

**Issue by ArnoChenFx** [yym68686/uni-api#8]
Traceback (most recent call last):

  File "/home/main.py", line 573, in <module>

    async def audio_transcriptions(

  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 992, in decorator

    self.add_api_route(

  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 931, in add_api_route

    route = route_class(

  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 552, in __init__

    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)

  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 277, in get_dependant

    param_details = analyze_param(

  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 472, in analyze_param

    ensure_multipart_is_installed()

  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 107, in ensure_multipart_is_installed

    raise RuntimeError(multipart_not_installed_error) from None

RuntimeError: Form data requires "python-multipart" to be installed. 

You can install "python-multipart" with: 

pip install python-multipart

**Comment by yym68686** [comment]
已修复。
